#!/bin/bash
# Locate the temporary directories
MC_HOME="/opt/mcserver"
mkdir -p $MC_HOME

# Locate the persistent directories
MC_BASE="/opt/minecraft"
mkdir -p $MC_BASE
MC_JARS="$MC_BASE/jars"
mkdir -p $MC_JARS
MC_GLOBAL="$MC_BASE/global"
mkdir -p $MC_GLOBAL
MC_GAME="$MC_BASE/games/${MC_GAME:-hub}"
mkdir -p $MC_GAME

# Variables for jar loading
SPIGOT_BUILDTOOLS_URL=${SPIGOT_BUILDTOOLS_URL:-"https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar"}
MC_VERSION=${VERSION:-1.9.2}
MC_JAR=${MC_JAR:-"spigot-$MC_VERSION.jar"}

# Variables for jar execution
MC_OPTS=${MC_OPTS:-"-server -Xmx1024m -XX:+UseParNewGC -XX:+UseConcMarkSweepGC"}
TMUX_SESSION=spigot

setup_server(){
 build_server
 sync
 run_spigot
}

build_server() {
    # Compile spigot if it does not exist.
    if [ ! -f "$MC_JARS/$MC_JAR" ]; then
        echo "Building Spigot" && \
            mkdir -p /tmp/spigot && \
            curl -S $SPIGOT_BUILDTOOLS_URL -o /tmp/spigot/BuildTools.jar && \
            pushd /tmp/spigot > /dev/null && \
            java -jar BuildTools.jar --rev $MC_VERSION && \
            cp /tmp/spigot/craftbukkit-*.jar  /tmp/spigot/spigot-*.jar $MC_JARS && \
            popd > /dev/null && \
            rm -rf /tmp/spigot
            
        if [ $? -ne 0 ]; then
            >&2 echo "Unable to build Spigot."
            exit 1
        fi
    fi
}

sync() {
    # Sync files from $MC_BASE to $MC_HOME. Do this on container's first run.
    # Server jar
    mkdir -p $MC_HOME
    cp $MC_JARS/$MC_JAR $MC_HOME/$MC_JAR
    # Move all global files and folders into the temporary file system
    mkdir -p $MC_GLOBAL
    rsync -a $MC_GLOBAL/ $MC_HOME/
    # Move all game specific files and folders into the temporary file system
    mkdir -p $MC_GAME
    rsync -a $MC_GAME/ $MC_HOME/
    chmod -R +777 $MC_HOME/
}

run_spigot() {
    echo "Running Spigot"
    echo "MINECRAFT_OPTS: $MC_OPTS"
    MC_COMMAND="java $MC_OPTS -jar $MC_HOME/$MC_JAR nogui"
    tmux new -s $TMUX_SESSION "su - minecraft -c 'exec $MC_COMMAND'"
}
#Start the server
setup_server
